DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS comments CASCADE;

CREATE TABLE IF NOT EXISTS users (
  user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(512) NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (user_id),
  CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items (
    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    item_name CHARACTER VARYING(128) NOT NULL,
    description CHARACTER VARYING(200) NOT NULL,
    available BOOLEAN NOT NULL,
    owner_id BIGINT NOT NULL,
    CONSTRAINT pk_item PRIMARY KEY (item_id),
    CONSTRAINT "fk_items_users_user_id" FOREIGN KEY (owner_id) REFERENCES users ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bookings (
    booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_time TIMESTAMP not null,
    end_time TIMESTAMP not null,
    item_id BIGINT not null,
    booker_id BIGINT not null,
    booking_status CHARACTER VARYING(8),
    constraint pk_booking primary key (booking_id),
    constraint "bookings_ITEMS_ITEM_ID_fk" foreign key (item_id) references items ON DELETE CASCADE ,
    constraint "bookings_USERS_USER_ID_fk" foreign key (booker_id) references users ON DELETE CASCADE ,
    constraint CHECK_DATE check (start_time < BOOKINGS.end_time)
);

CREATE TABLE IF NOT EXISTS comments (
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text CHARACTER VARYING(1024) not null,
    item_id BIGINT not null,
    author_id BIGINT not null,
    created TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() not null,
    constraint pk_comment primary key (item_id),
    constraint "comments_ITEMS_ITEM_ID_fk" foreign key (item_id) references items ON DELETE CASCADE ,
    constraint "comments_USERS_USER_ID_fk" foreign key (author_id) references users ON DELETE CASCADE
);
